"""
backend/llm.py
Gemini API wrapper for generating resume Q&A answers.
Falls back gracefully if the API key is missing.
"""
import os
from typing import List, Dict, Any

import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

_GEMINI_MODEL = "gemini-2.5-flash"   # Free-tier model


def _configure_gemini() -> None:
    api_key = os.getenv("GEMINI_API_KEY", "")
    if not api_key or api_key == "your_gemini_api_key_here":
        raise EnvironmentError(
            "GEMINI_API_KEY is not set. "
            "Copy .env.example → .env and add your key from "
            "https://aistudio.google.com/app/apikey"
        )
    genai.configure(api_key=api_key)


def generate_answer(question: str, context_chunks: List[Dict[str, Any]]) -> str:
    """
    Use Gemini to answer a question given retrieved resume context.

    Args:
        question:       User's question about the resume.
        context_chunks: List of chunk dicts (must contain 'text' key).

    Returns:
        Answer string generated by the LLM.
    """
    _configure_gemini()

    context_text = "\n\n---\n\n".join(
        chunk["text"] for chunk in context_chunks if chunk.get("text")
    )

    prompt = f"""You are an expert AI Resume Assistant. Your job is to answer questions 
about a candidate's resume accurately and concisely.

Use ONLY the information provided in the resume context below.
If the answer is not found in the context, say: "I couldn't find that information in the resume."
Do not make up or infer information that is not explicitly stated.

RESUME CONTEXT:
{context_text}

QUESTION:
{question}

ANSWER:"""

    model = genai.GenerativeModel(_GEMINI_MODEL)
    response = model.generate_content(prompt)
    return response.text.strip()


def generate_summary(context_chunks: List[Dict[str, Any]]) -> str:
    """
    Generate a professional summary of the resume.

    Args:
        context_chunks: All chunks from the resume.

    Returns:
        A structured summary string.
    """
    _configure_gemini()

    full_text = "\n\n".join(
        chunk["text"] for chunk in context_chunks if chunk.get("text")
    )

    prompt = f"""You are an expert career coach and recruiter.
Based on the resume below, generate a concise professional profile summary.

Structure your response with these sections:
1. **Profile Overview** (2-3 sentences)
2. **Core Technical Skills** (bullet list)
3. **Key Experiences** (bullet list, max 4 items)
4. **Education**
5. **Notable Achievements** (if any)

RESUME:
{full_text}

PROFESSIONAL SUMMARY:"""

    model = genai.GenerativeModel(_GEMINI_MODEL)
    response = model.generate_content(prompt)
    return response.text.strip()


def generate_interview_questions(context_chunks: List[Dict[str, Any]]) -> str:
    """Generate tailored interview questions based on the resume."""
    _configure_gemini()

    full_text = "\n\n".join(
        chunk["text"] for chunk in context_chunks if chunk.get("text")
    )

    prompt = f"""You are a senior technical interviewer.
Based on this resume, generate 10 targeted interview questions that probe the candidate's:
- Technical skills and depth of knowledge
- Project experience
- Problem-solving approach
- Achievements and impact

Format as a numbered list. Make each question specific to what's on this resume.

RESUME:
{full_text}

INTERVIEW QUESTIONS:"""

    model = genai.GenerativeModel(_GEMINI_MODEL)
    response = model.generate_content(prompt)
    return response.text.strip()


def generate_skills(context_chunks: List[Dict[str, Any]]) -> str:
    """
    Extract a list of technical skills from the resume.

    Args:
        context_chunks: All chunks from the resume.

    Returns:
        A list of extracted skills as a string.
    """
    _configure_gemini()

    full_text = "\n\n".join(
        chunk["text"] for chunk in context_chunks if chunk.get("text")
    )

    prompt = f"""You are an expert technical recruiter.
Based on the resume below, extract all the technical skills mentioned.
Return ONLY a clean, bulleted list of skills (e.g., programming languages, frameworks, tools, databases). Do not include soft skills. Do not add any introductory text.

RESUME:
{full_text}

TECHNICAL SKILLS:"""

    model = genai.GenerativeModel(_GEMINI_MODEL)
    response = model.generate_content(prompt)
    return response.text.strip()
