"""
backend/llm.py
LLM wrapper for generating resume Q&A answers.

Primary:  Google Gemini (gemini-2.5-flash)
Fallback: OpenAI (gpt-4o-mini) – enabled by setting OPENAI_API_KEY in .env

The module auto-detects which key is available.
"""
import os
from typing import List, Dict, Any

from dotenv import load_dotenv

load_dotenv()

# ── Model names ────────────────────────────────────────────────────────────────
_GEMINI_MODEL = "gemini-2.5-flash"
_OPENAI_MODEL = "gpt-4o-mini"


# ── Provider detection ─────────────────────────────────────────────────────────

def _get_provider() -> str:
    """Determine which LLM provider to use based on available API keys."""
    gemini_key = os.getenv("GEMINI_API_KEY", "")
    openai_key = os.getenv("OPENAI_API_KEY", "")

    if gemini_key and gemini_key != "your_gemini_api_key_here":
        return "gemini"
    if openai_key and openai_key != "your_openai_api_key_here":
        return "openai"

    raise EnvironmentError(
        "No LLM API key found. Set GEMINI_API_KEY or OPENAI_API_KEY in your .env file.\n"
        "  • Gemini (free): https://aistudio.google.com/app/apikey\n"
        "  • OpenAI: https://platform.openai.com/api-keys"
    )


def _call_gemini(prompt: str) -> str:
    """Send a prompt to Gemini and return the text response."""
    import google.generativeai as genai
    genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
    model = genai.GenerativeModel(_GEMINI_MODEL)
    response = model.generate_content(prompt)
    return response.text.strip()


def _call_openai(prompt: str) -> str:
    """Send a prompt to OpenAI and return the text response."""
    try:
        from openai import OpenAI
    except ImportError:
        raise ImportError(
            "openai package not installed. Run: pip install openai"
        )
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    response = client.chat.completions.create(
        model=_OPENAI_MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
    )
    return response.choices[0].message.content.strip()


def _generate(prompt: str) -> str:
    """Route the prompt to the available LLM provider."""
    provider = _get_provider()
    if provider == "gemini":
        return _call_gemini(prompt)
    return _call_openai(prompt)


# ── Public functions ───────────────────────────────────────────────────────────

def generate_answer(question: str, context_chunks: List[Dict[str, Any]]) -> str:
    """
    Answer a user question using retrieved resume context.

    Args:
        question:       User's question about the resume.
        context_chunks: List of chunk dicts (must contain 'text' key).

    Returns:
        Answer string generated by the LLM.
    """
    context_text = "\n\n---\n\n".join(
        chunk["text"] for chunk in context_chunks if chunk.get("text")
    )

    prompt = f"""You are an expert AI Resume Assistant. Your job is to answer questions \
about a candidate's resume accurately and concisely.

Rules:
- Use ONLY the information provided in the RESUME CONTEXT below.
- If the answer is not found in the context, respond with: \
"I couldn't find that information in the resume."
- Do NOT make up or infer information not explicitly stated.
- Be concise and specific.

RESUME CONTEXT:
{context_text}

QUESTION:
{question}

ANSWER:"""

    return _generate(prompt)


def generate_summary(context_chunks: List[Dict[str, Any]]) -> str:
    """
    Generate a structured professional summary of the resume.

    Args:
        context_chunks: All (or top) chunks from the resume.

    Returns:
        Formatted professional summary string.
    """
    full_text = "\n\n".join(
        chunk["text"] for chunk in context_chunks if chunk.get("text")
    )

    prompt = f"""You are an expert career coach and recruiter.
Based on the resume below, generate a concise professional profile summary.

Structure your response with these exact sections:
## Profile Overview
(2–3 sentences describing the candidate's background and value proposition)

## Core Technical Skills
(Bulleted list of key technical competencies)

## Key Experiences
(Up to 4 bullet points of most impactful roles/projects)

## Education
(Degrees, institutions, graduation years)

## Notable Achievements
(Key accomplishments, awards, or standout metrics — skip if none found)

Keep the tone professional and recruiter-friendly.

RESUME:
{full_text}

PROFESSIONAL SUMMARY:"""

    return _generate(prompt)


def generate_interview_questions(context_chunks: List[Dict[str, Any]]) -> str:
    """
    Generate 10 targeted interview questions tailored to the resume.

    Args:
        context_chunks: Relevant chunks from the resume.

    Returns:
        Numbered list of interview questions as a string.
    """
    full_text = "\n\n".join(
        chunk["text"] for chunk in context_chunks if chunk.get("text")
    )

    prompt = f"""You are a senior technical interviewer preparing for a candidate interview.

Based on the resume below, generate exactly 10 targeted interview questions that:
- Probe the candidate's depth of technical knowledge
- Reference specific projects, technologies, or experiences from their resume
- Cover a mix of: technical depth, system design, problem-solving, and behavioural
- Are specific to THIS candidate, not generic questions

Format your response as a numbered list (1. ... 2. ... etc.)
After each question, add a brief note in italics explaining WHY you're asking it.

RESUME:
{full_text}

INTERVIEW QUESTIONS:"""

    return _generate(prompt)


def generate_skills(context_chunks: List[Dict[str, Any]]) -> str:
    """
    Extract and categorize technical skills from the resume.

    Args:
        context_chunks: All chunks from the resume.

    Returns:
        Categorised list of technical skills as a string.
    """
    full_text = "\n\n".join(
        chunk["text"] for chunk in context_chunks if chunk.get("text")
    )

    prompt = f"""You are an expert technical recruiter performing a skills audit.

Based on the resume below, extract ALL technical skills and group them into categories:

## Programming Languages
## Frameworks & Libraries
## Databases
## Cloud & DevOps
## Tools & Platforms
## Other Technical Skills

Rules:
- List ONLY skills explicitly mentioned in the resume — do NOT infer or add extras.
- Use bullet points within each category.
- Skip a category entirely if no skills fit it.
- Do NOT include soft skills (communication, teamwork, etc.)

RESUME:
{full_text}

TECHNICAL SKILLS:"""

    return _generate(prompt)
